import React, { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import { Plus, Trash2, Edit3, Calendar, MapPin, X } from 'lucide-react';
import { db } from '../firebase/config';
import { collection, onSnapshot, addDoc, updateDoc, deleteDoc, doc } from 'firebase/firestore';
import './ManageEvents.css';

const ManageEvents = () => {
  const { currentUser } = useAuth();
  const [events, setEvents] = useState([]);
  const [showForm, setShowForm] = useState(false);
  const [loading, setLoading] = useState(true);
  
  // Form State
  const [formData, setFormData] = useState({
    id: '', title: '', date: '', time: '', venue: '', category: 'Technical', desc: ''
  });

  useEffect(() => {
    const eventsRef = collection(db, 'events');
    const unsubscribe = onSnapshot(eventsRef, (snapshot) => {
      const eventsData = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
      setEvents(eventsData);
      setLoading(false);
    }, (error) => {
      console.error("Firestore Error in ManageEvents:", error);
      setLoading(false);
    });

    return () => unsubscribe();
  }, []);

  const myEvents = events.filter(e => e.creatorId === currentUser.uid);

  const handleInputChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    try {
      if (formData.id) {
        // Edit mode
        const eventRef = doc(db, 'events', formData.id);
        const { id, ...updateData } = formData;
        await updateDoc(eventRef, updateData);
      } else {
        // Create mode
        const newEvent = {
          ...formData,
          creatorId: currentUser.uid,
          registered: []
        };
        delete newEvent.id; // id is generated by firestore naturally
        await addDoc(collection(db, 'events'), newEvent);
      }
      setShowForm(false);
      resetForm();
    } catch (error) {
      console.error("Error saving event:", error);
      alert("Failed to save event. Please check your Firestore permissions.");
    }
  };

  const handleEdit = (event) => {
    setFormData({
      id: event.id,
      title: event.title,
      date: event.date,
      time: event.time,
      venue: event.venue,
      category: event.category,
      desc: event.desc
    });
    setShowForm(true);
  };

  const handleDelete = async (id) => {
    if(window.confirm('Are you sure you want to delete this event?')) {
      try {
        await deleteDoc(doc(db, 'events', id));
      } catch (error) {
        console.error("Error deleting event:", error);
        alert("Failed to delete event. Check console for details.");
      }
    }
  };

  const resetForm = () => {
    setFormData({ id: '', title: '', date: '', time: '', venue: '', category: 'Technical', desc: '' });
  };

  if (loading) return <div className="p-8 text-center text-muted">Loading your events...</div>;

  return (
    <div className="manage-events animate-fade-in">
      <div className="manage-header">
        <div>
          <h2 className="text-gradient" style={{fontSize:'2rem', marginBottom:'0.5rem'}}>Manage Events</h2>
          <p className="text-muted">Create and manage your college events on the Cloud.</p>
        </div>
        <button 
          className="btn-primary" 
          onClick={() => { resetForm(); setShowForm(true); }}
        >
          <Plus size={18} /> New Event
        </button>
      </div>

      {showForm && (
        <div className="event-form-overlay">
          <div className="event-form-container glass-card">
            <div className="form-header">
              <h3>{formData.id ? 'Edit Event' : 'Create New Event'}</h3>
              <button className="btn-icon text-muted hover:text-main" onClick={() => setShowForm(false)}>
                <X size={20} />
              </button>
            </div>
            
            <form onSubmit={handleSubmit} className="event-form">
              <div className="form-group grid-col-1">
                <label>Event Title</label>
                <input required type="text" name="title" className="form-input" value={formData.title} onChange={handleInputChange} />
              </div>
              
              <div className="grid-col-2">
                <div className="form-group">
                  <label>Date</label>
                  <input required type="date" name="date" className="form-input" value={formData.date} onChange={handleInputChange} />
                </div>
                <div className="form-group">
                  <label>Time</label>
                  <input required type="time" name="time" className="form-input" value={formData.time} onChange={handleInputChange} />
                </div>
              </div>

              <div className="grid-col-2">
                <div className="form-group">
                  <label>Venue</label>
                  <input required type="text" name="venue" className="form-input" value={formData.venue} onChange={handleInputChange} />
                </div>
                <div className="form-group">
                  <label>Category</label>
                  <select name="category" className="form-input" value={formData.category} onChange={handleInputChange}>
                    <option value="Technical">Technical</option>
                    <option value="Cultural">Cultural</option>
                    <option value="Sports">Sports</option>
                    <option value="Academic">Academic</option>
                  </select>
                </div>
              </div>

              <div className="form-group">
                <label>Description</label>
                <textarea required name="desc" className="form-input" rows="3" value={formData.desc} onChange={handleInputChange}></textarea>
              </div>

              <div className="form-actions">
                <button type="button" className="btn-secondary" onClick={() => setShowForm(false)}>Cancel</button>
                <button type="submit" className="btn-primary">{formData.id ? 'Update Event' : 'Publish Event'}</button>
              </div>
            </form>
          </div>
        </div>
      )}

      <div className="table-container glass-card">
        {myEvents.length === 0 ? (
          <div className="empty-state">
            <p className="text-muted">You haven't created any events yet.</p>
          </div>
        ) : (
          <table className="events-table">
            <thead>
              <tr>
                <th>Event Title</th>
                <th>Date & Time</th>
                <th>Venue</th>
                <th>Category</th>
                <th>Registrations</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {myEvents.map(event => (
                <tr key={event.id}>
                  <td className="font-medium text-main">{event.title}</td>
                  <td>
                    <div className="flex-col gap-2">
                      <span className="flex items-center gap-2 text-sm"><Calendar size={14} className="text-secondary" /> {event.date}</span>
                    </div>
                  </td>
                  <td><span className="flex items-center gap-2 text-sm text-muted"><MapPin size={14}/> {event.venue}</span></td>
                  <td><span className={`ec-category badge-${event.category.toLowerCase()}`}>{event.category}</span></td>
                  <td className="text-center font-bold text-main">{event.registered?.length || 0}</td>
                  <td>
                    <div className="action-buttons">
                      <button className="btn-icon text-accent" onClick={() => handleEdit(event)} title="Edit">
                        <Edit3 size={18} />
                      </button>
                      <button className="btn-icon text-danger" onClick={() => handleDelete(event.id)} title="Delete">
                        <Trash2 size={18} />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
};

export default ManageEvents;
